version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: "/etc/letsencrypt/cerbot_updater.sh"

